### ISSUE TITLE
cmake failed

### ISSUE THREAD

**Issue by suryaprakaz** [ros-planning/warehouse_ros#25] opened 2015-09-19 17:42 UTC
I am trying to gather tools for moveit and when collecting the warehouse_ros dependency I came across this error while invoking catkin_make

CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
MongoDB_INCLUDE_DIR (ADVANCED)
   used as include directory in directory /home/suryaprakaz/Documents/ROS/Robots/src/warehouse_ros
   used as include directory in directory /home/suryaprakaz/Documents/ROS/Robots/src/warehouse_ros
   used as include directory in directory /home/suryaprakaz/Documents/ROS/Robots/src/warehouse_ros
   used as include directory in directory /home/suryaprakaz/Documents/ROS/Robots/src/warehouse_ros
   used as include directory in directory /home/suryaprakaz/Documents/ROS/Robots/src/warehouse_ros
   used as include directory in directory /home/suryaprakaz/Documents/ROS/Robots/src/warehouse_ros
   used as include directory in directory /home/suryaprakaz/Documents/ROS/Robots/src/warehouse_ros
   used as include directory in directory /home/suryaprakaz/Documents/ROS/Robots/src/warehouse_ros
MongoDB_LIBRARIES (ADVANCED)
    linked by target "warehouse_ros" in directory /home/suryaprakaz/Documents/ROS/Robots/src/warehouse_ros

-- Configuring incomplete, errors occurred!
See also "/home/suryaprakaz/Documents/ROS/Robots/build/CMakeFiles/CMakeOutput.log".
See also "/home/suryaprakaz/Documents/ROS/Robots/build/CMakeFiles/CMakeError.log".

I am unsure about this and haven't found a solution yet.

**Comment by ugocupcic** [comment] 2015-10-07 12:59
It seems like mongodb isn't found. Did you install the rosdep?

**Comment by suryaprakaz** [comment] 2015-10-07 16:45
In file included from /home/suryaprakaz/moveit/src/warehouse_ros/include/mongo_ros/mongo_ros.h:42:0,
                 from /home/suryaprakaz/moveit/src/warehouse_ros/src/mongo_ros_dummy.cpp:31:
/home/suryaprakaz/moveit/src/warehouse_ros/include/mongo_ros/metadata.h: In constructor ‘mongo_ros::WrappedBSON::WrappedBSON(const string&)’:
/home/suryaprakaz/moveit/src/warehouse_ros/include/mongo_ros/metadata.h:83:30: error: ‘fromjson’ is not a member of ‘mongo’
     builder_->appendElements(mongo::fromjson(json.c_str()));
                              ^
In file included from /home/suryaprakaz/moveit/src/warehouse_ros/include/mongo_ros/mongo_ros.h:42:0,
                 from /home/suryaprakaz/moveit/src/warehouse_ros/src/mongo_ros.cpp:39:
/home/suryaprakaz/moveit/src/warehouse_ros/include/mongo_ros/metadata.h: In constructor ‘mongo_ros::WrappedBSON::WrappedBSON(const string&)’:
/home/suryaprakaz/moveit/src/warehouse_ros/include/mongo_ros/metadata.h:83:30: error: ‘fromjson’ is not a member of ‘mongo’
     builder_->appendElements(mongo::fromjson(json.c_str()));
                              ^
In file included from /home/suryaprakaz/moveit/src/warehouse_ros/include/mongo_ros/query_results.h:101:0,
                 from /home/suryaprakaz/moveit/src/warehouse_ros/include/mongo_ros/message_collection.h:42,
                 from /home/suryaprakaz/moveit/src/warehouse_ros/src/mongo_ros.cpp:41:
/home/suryaprakaz/moveit/src/warehouse_ros/include/mongo_ros/impl/query_results_impl.hpp: In constructor ‘mongo_ros::ResultIterator<M>::ResultIterator(boost::shared_ptr<mongo::DBClientConnection>, const string&, const mongo::Query&, boost::shared_ptr<mongo::GridFS>, bool)’:
/home/suryaprakaz/moveit/src/warehouse_ros/include/mongo_ros/impl/query_results_impl.hpp:57:17: error: invalid use of incomplete type ‘std::auto_ptr<mongo::DBClientCursor>::element_type {aka class mongo::DBClientCursor}’
   if ((*cursor_)->more())
                 ^
In file included from /opt/ros/jade/include/mongo/client/gridfs.h:24:0,
                 from /home/suryaprakaz/moveit/devel_isolated/warehouse_ros/include/mongo_ros/config.h:47,
                 from /home/suryaprakaz/moveit/src/warehouse_ros/include/mongo_ros/metadata.h:49,
                 from /home/suryaprakaz/moveit/src/warehouse_ros/include/mongo_ros/mongo_ros.h:42,
                 from /home/suryaprakaz/moveit/src/warehouse_ros/src/mongo_ros.cpp:39:
/opt/ros/jade/include/mongo/client/dbclientinterface.h:379:11: error: forward declaration of ‘std::auto_ptr<mongo::DBClientCursor>::element_type {aka class mongo::DBClientCursor}’
     class DBClientCursor;
           ^
In file included from /home/suryaprakaz/moveit/src/warehouse_ros/include/mongo_ros/query_results.h:101:0,
                 from /home/suryaprakaz/moveit/src/warehouse_ros/include/mongo_ros/message_collection.h:42,
                 from /home/suryaprakaz/moveit/src/warehouse_ros/src/mongo_ros.cpp:41:
/home/suryaprakaz/moveit/src/warehouse_ros/include/mongo_ros/impl/query_results_impl.hpp:58:23: error: invalid use of incomplete type ‘std::auto_ptr<mongo::DBClientCursor>::element_type {aka class mongo::DBClientCursor}’
     next_ = (*cursor_)->nextSafe();
                       ^
In file included from /opt/ros/jade/include/mongo/client/gridfs.h:24:0,
                 ffrom /opt/ros/jade/include/mongo/client/gridfs.h:24:0,
                 from /home/suryaprakaz/moveit/devel_isolated/warehouse_ros/include/mongo_ros/config.h:47,
                 from /home/suryaprakaz/moveit/src/warehouse_ros/include/mongo_ros/metadata.h:49,
                 from /home/suryaprakaz/moveit/src/warehouse_ros/include/mongo_ros/mongo_ros.h:42,
                 from /home/suryaprakaz/moveit/src/warehouse_ros/src/mongo_ros.cpp:39:
/opt/ros/jade/include/mongo/client/dbclientinterface.h:379:11: error: forward declaration of ‘std::auto_ptr<mongo::DBClientCursor>::element_type {aka class mongo::DBClientCursor}’
     class DBClientCursor;
           ^
In file included from /home/suryaprakaz/moveit/src/warehouse_ros/include/mongo_ros/query_results.h:101:0,
                 from /home/suryaprakaz/moveit/src/warehouse_ros/include/mongo_ros/message_collection.h:42,
                 from /home/suryaprakaz/moveit/src/warehouse_ros/src/mongo_ros.cpp:41:
/home/suryaprakaz/moveit/src/warehouse_ros/include/mongo_ros/impl/query_results_impl.hpp:58:23: error: invalid use of incomplete type ‘std::auto_ptr<mongo::DBClientCursor>::element_type {aka class mongo::DBClientCursor}’
     next_ = (*cursor_)->nextSafe();
                       ^
In file included from /opt/ros/jade/include/mongo/client/gridfs.h:24:0,
                 from /home/suryaprakaz/moveit/devel_isolated/warehouse_ros/include/mongo_ros/config.h:47,
                 from /home/suryaprakaz/moveit/src/warehouse_ros/include/mongo_ros/metadata.h:49,
                 from /home/suryaprakaz/moveit/src/warehouse_ros/include/mongo_ros/mongo_ros.h:42,
                 from /home/suryaprakaz/moveit/src/warehouse_ros/src/mongo_ros.cpp:39:
/opt/ros/jade/include/mongo/client/dbclientinterface.h:379:11: error: forward declaration of ‘std::auto_ptr<mongo::DBClientCursor>::element_type {aka class mongo::DBClientCursor}’
     class DBClientCursor;
           ^
In file included from /home/suryaprakaz/moveit/src/warehouse_ros/include/mongo_ros/query_results.h:101:0,
                 from /home/suryaprakaz/moveit/src/warehouse_ros/include/mongo_ros/message_collection.h:42,
                 from /home/suryaprakaz/moveit/src/warehouse_ros/src/mongo_ros.cpp:41:
/home/suryaprakaz/moveit/src/warehouse_ros/include/mongo_ros/impl/query_results_impl.hpp: In member function ‘void mongo_ros::ResultIterator<M>::increment()’:
/home/suryaprakaz/moveit/src/warehouse_ros/include/mongo_ros/impl/query_results_impl.hpp:78:17: error: invalid use of incomplete type ‘std::auto_ptr<mongo::DBClientCursor>::element_type {aka class mongo::DBClientCursor}’
   if ((*cursor_)->more())
                 ^
In file included from /opt/ros/jade/include/mongo/client/gridfs.h:24:0,
                 from /home/suryaprakaz/moveit/devel_isolated/warehouse_ros/include/mongo_ros/config.h:47,
                 from /home/suryaprakaz/moveit/src/warehouse_ros/include/mongo_ros/metadata.h:49,
                 from /home/suryaprakaz/moveit/src/warehouse_ros/include/mongo_ros/mongo_ros.h:42,
                 from /home/suryaprakaz/moveit/src/warehouse_ros/src/mongo_ros.cpp:39:
/opt/ros/jade/include/mongo/client/dbclientinterface.h:379:11: error: forward declaration of ‘std::auto_ptr<mongo::DBClientCursor>::element_type {aka class mongo::DBClientCursor}’
     class DBClientCursor;
           ^
In file included from /home/suryaprakaz/moveit/src/warehouse_ros/include/mongo_ros/query_results.h:101:0,
                 from /home/suryaprakaz/moveit/src/warehouse_ros/include/mongo_ros/message_collection.h:42,
                 from /home/suryaprakaz/moveit/src/warehouse_ros/src/mongo_ros.cpp:41:
/home/suryaprakaz/moveit/src/warehouse_ros/include/mongo_ros/impl/query_results_impl.hpp:79:23: error: invalid use of incomplete type ‘std::auto_ptr<mongo::DBClientCursor>::element_type {aka class mongo::DBClientCursor}’
     next_ = (*cursor_)->nextSafe();
                       ^
In file included from /opt/ros/jade/include/mongo/client/gridfs.h:24:0,
                 from /home/suryaprakaz/moveit/devel_isolated/warehouse_ros/include/mongo_ros/config.h:47,
                 from /home/suryaprakaz/moveit/src/warehouse_ros/include/mongo_ros/metadata.h:49,
                 from /home/suryaprakaz/moveit/src/warehouse_ros/include/mongo_ros/mongo_ros.h:42,
                 from /home/suryaprakaz/moveit/src/warehouse_ros/src/mongo_ros.cpp:39:
/opt/ros/jade/include/mongo/client/dbclientinterface.h:379:11: error: forward declaration of ‘std::auto_ptr<mongo::DBClientCursor>::element_type {aka class mongo::DBClientCursor}’
     class DBClientCursor;
           ^
In file included from /home/suryaprakaz/moveit/src/warehouse_ros/include/mongo_ros/message_collection.h:139:0,
                 from /home/suryaprakaz/moveit/src/warehouse_ros/src/mongo_ros.cpp:41:
/home/suryaprakaz/moveit/src/warehouse_ros/include/mongo_ros/impl/message_collection_impl.hpp: In member function ‘mongo_ros::MessageCollection<M>& mongo_ros::MessageCollection<M>::ensureIndex(const string&)’:
/home/suryaprakaz/moveit/src/warehouse_ros/include/mongo_ros/impl/message_collection_impl.hpp:125:10: error: ‘class mongo::DBClientConnection’ has no member named ‘ensureIndex’
   conn_->ensureIndex(ns_, BSON(field << 1));
          ^
/home/suryaprakaz/moveit/src/warehouse_ros/src/mongo_ros.cpp: In function ‘std::string mongo_ros::messageType(mongo::DBClientConnection&, const string&, const string&)’:
/home/suryaprakaz/moveit/src/warehouse_ros/src/mongo_ros.cpp:131:30: error: invalid use of incomplete type ‘std::auto_ptr<mongo::DBClientCursor>::element_type {aka class mongo::DBClientCursor}’
   mongo::BSONObj obj = cursor->next();
                              ^
In file included from /opt/ros/jade/include/mongo/client/gridfs.h:24:0,
                 from /home/suryaprakaz/moveit/devel_isolated/warehouse_ros/include/mongo_ros/config.h:47,
                 from /home/suryaprakaz/moveit/src/warehouse_ros/include/mongo_ros/metadata.h:49,
                 from /home/suryaprakaz/moveit/src/warehouse_ros/include/mongo_ros/mongo_ros.h:42,
                 from /home/suryaprakaz/moveit/src/warehouse_ros/src/mongo_ros.cpp:39:
/opt/ros/jade/include/mongo/client/dbclientinterface.h:379:11: error: forward declaration of ‘std::auto_ptr<mongo::DBClientCursor>::element_type {aka class mongo::DBClientCursor}’
     class DBClientCursor;
           ^
CMakeFiles/warehouse_ros.dir/build.make:77: recipe for target 'CMakeFiles/warehouse_ros.dir/src/mongo_ros_dummy.cpp.o' failed
make[2]: *** [CMakeFiles/warehouse_ros.dir/src/mongo_ros_dummy.cpp.o] Error 1
CMakeFiles/warehouse_ros.dir/build.make:54: recipe for target 'CMakeFiles/warehouse_ros.dir/src/mongo_ros.cpp.o' failed
make[2]: *** [CMakeFiles/warehouse_ros.dir/src/mongo_ros.cpp.o] Error 1
CMakeFiles/Makefile2:932: recipe for target 'CMakeFiles/warehouse_ros.dir/all' failed
make[1]: *** [CMakeFiles/warehouse_ros.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
<== Failed to process package 'warehouse_ros': 
  Command '['/home/suryaprakaz/moveit/devel_isolated/octovis/env.sh', 'make', '-j4', '-l4']' returned non-zero exit status 2

Reproduce this error by running:
==> cd /home/suryaprakaz/moveit/build_isolated/warehouse_ros && /home/suryaprakaz/moveit/devel_isolated/octovis/env.sh make -j4 -l4

Command failed, exiting.

**Comment by suryaprakaz** [comment] 2015-10-07 16:49
Now I am getting this error and I am unable to solve this problem. I use Vivid with Jade. And I saw it here http://www.ros.org/debbuild/jade?q=moveit that the warehouse package for Jade Vivid is not released yet. Might that be the problem?

**Comment by mikeferguson** [comment] 2015-10-07 21:54
duplicate of #20 -- please see comments there. We are still working to fix this.

**Closed by mikeferguson** 2015-10-07 21:54 UTC

**Comment by GIT862** [comment] 2021-07-18 16:20
/home/xxx/learning/ros_ws/src/third_packages/warehouse_ros_mongo/src/message_collection.cpp:81:10: error: ‘class mongo::DBClientConnection’ has no member named ‘createIndex’; did you mean ‘reIndex’?
   conn_->createIndex(ns_, BSON(field << 1));

i have the same problem,yet,how can i sovle???
thanks a lot

**Comment by liod1234** [comment] 2021-10-03 10:27
I try to compile the warehouse on melodic devel but I get the same error, how to fix it?

**Comment by v4hn** [comment] 2021-10-03 19:39
The error is about `warehouse_ros_mongo`, not about `warehouse_ros`.
https://github.com/gleichdick/warehouse_ros_sqlite might be the better option for you at this point, though the mongo backend should be fixed if this is actually an upstream issue.
